// Shared by the interactive and simple portfolio views.
export const publishedExtensionsData = [
    {
      id: "focusforge",
      name: "FocusForge",
      platform: "VS Code Marketplace",
      platformBadge: "VS Code Extension",
      badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
      description: "Local-first VS Code productivity dashboard for focus time, Pomodoro cycles, projects, GitHub issues, commits, planner sessions and reports.",
      url: "https://marketplace.visualstudio.com/items?itemName=NK2552003.focusforge",
      tags: ["VS Code", "TypeScript", "Pomodoro", "Offline-first"],
      highlight: "Productivity",
      buttonText: "VS Code Marketplace",
    },
    {
      id: "pasteshield",
      name: "PasteShield",
      platform: "VS Code Marketplace",
      platformBadge: "VS Code Extension",
      badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30",
      description: "Intercepts every paste and catches API keys, hardcoded passwords, and unsafe code patterns before they reach your file, fully offline.",
      url: "https://marketplace.visualstudio.com/items?itemName=NK2552003.pasteshield",
      tags: ["Security", "Privacy", "Zero-Leak", "Offline"],
      highlight: "Security",
      buttonText: "VS Code Marketplace",
    },
    {
      id: "forest-ash-theme",
      name: "Forest Ash Theme",
      platform: "VS Code Marketplace",
      platformBadge: "VS Code Theme",
      badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30",
      description: "21 eye-friendly dark and light themes inspired by forest ash textures and anime mood boards for extended coding comfort.",
      url: "https://marketplace.visualstudio.com/items?itemName=NK2552003.forest-ash-theme-vscode",
      tags: ["Themes", "21 Variants", "UI/UX", "Dark & Light"],
      highlight: "21 Themes",
      buttonText: "VS Code Marketplace",
    },
    {
      id: "quiet_dock",
      name: "quiet_dock",
      platform: "pub.dev",
      platformBadge: "Flutter Package",
      badgeColor: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/30",
      description: "Glassmorphic Flutter navigation dock with swipeable pages, quick actions, and a responsive wide-screen rail.",
      url: "https://pub.dev/packages/quiet_dock",
      tags: ["Flutter", "Dart", "Glassmorphic", "Navigation"],
      highlight: "pub.dev",
      buttonText: "View on pub.dev",
    },
    {
      id: "mac-deep-cleaner",
      name: "mac-deep-cleaner",
      platform: "PyPI",
      platformBadge: "Python CLI",
      badgeColor: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/30",
      description: "Python CLI for macOS cleanup with multiple safety layers, disk space recovery, cache inspection, and undo support.",
      url: "https://pypi.org/project/mac-deep-cleaner/",
      tags: ["Python", "CLI", "macOS", "System Cleanup"],
      highlight: "PyPI",
      buttonText: "View on PyPI",
    },
  ]

export const liveWebsitesData = [
    {
      id: "umd",
      name: "Ultimate Media Downloader",
      badge: "Live Website & CLI",
      badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/30",
      description: "Open-source CLI tool and documentation site supporting 115+ platforms, with multi-architecture release packages on Codeberg.",
      url: "https://ultimate-media-downloader.fun/",
      sourceUrl: "https://codeberg.org/nk2552003/umd",
      tags: ["CLI", "Documentation", "Next.js", "115+ Platforms"],
      highlight: "ultimate-media-downloader.fun",
      buttonText: "Visit Website",
    },
    {
      id: "iconoodle",
      name: "Iconoodle",
      badge: "Next.js & TypeScript",
      badgeColor: "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/30",
      description: "Library of hand-drawn SVG doodles, illustrations, and customizable icon packs ready to copy-paste into modern web apps.",
      url: "https://nk2552003.github.io/Iconoodle/",
      tags: ["Next.js", "SVG", "Doodles", "Open Source"],
      highlight: "Hand-drawn SVGs",
      buttonText: "Visit Iconoodle",
    },
    {
      id: "big-data-guide",
      name: "Big Data Survival Guide",
      badge: "Curriculum Portal",
      badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30",
      description: "Big Data Analytics course materials, lab guides, and deep-dive documentation covering theory, Hadoop ecosystem, and Apache Spark.",
      url: "https://nk2552003.github.io/Big-Data-Survival-Guide/",
      tags: ["Hadoop", "Spark", "Big Data", "Courseware"],
      highlight: "Hadoop & Spark",
      buttonText: "Explore Guide",
    },
    {
      id: "blisscampindia",
      name: "BlissCampIndia",
      badge: "Travel Platform",
      badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30",
      description: "Travel and camping discovery platform curated for pristine nature campsites and trekking routes across India and Nepal.",
      url: "https://nk2552003.github.io/BlissCampIndia/",
      tags: ["Web App", "Responsive", "Travel", "Camping"],
      highlight: "India & Nepal",
      buttonText: "Visit BlissCamp",
    },
    {
      id: "select2ai",
      name: "Select2AI Extension",
      badge: "Browser Extension",
      badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
      description: "Browser extension for instant AI-powered text analysis, definitions, summarization, and contextual explanations on selected text.",
      url: "https://github.com/NK2552003/Select2AI_Extension",
      tags: ["Chrome Extension", "AI", "JavaScript", "Manifest V3"],
      highlight: "AI Text Analysis",
      buttonText: "View Extension",
    },
    {
      id: "student-offers",
      name: "Student Offer Repository",
      badge: "Curated Directory",
      badgeColor: "bg-teal-500/10 text-teal-600 dark:text-teal-400 border-teal-500/30",
      description: "Source-linked catalog of free developer tools, student software plans, cloud credits, and trials with eligibility criteria.",
      url: "https://github.com/NK2552003/Student-Offer-Repository",
      tags: ["Curated", "Developer Tools", "Student Pack", "Discounts"],
      highlight: "Student Perks",
      buttonText: "View Repository",
    },
    {
      id: "quietnote",
      name: "QuietNote",
      badge: "Flutter App",
      badgeColor: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/30",
      description: "Offline-first Flutter application crafted as a calm, distraction-free sanctuary for private notes, personal plans, and focused work.",
      url: "https://github.com/NK2552003/QuietNote",
      tags: ["Flutter", "Dart", "Offline-first", "Notes"],
      highlight: "Calm Productivity",
      buttonText: "View on GitHub",
    },
    {
      id: "brew-why",
      name: "brew-why",
      badge: "Python CLI & TUI",
      badgeColor: "bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/30",
      description: "Python CLI and interactive Textual terminal UI to explore Homebrew dependency graphs, find dependency roots, and clean orphaned packages.",
      url: "https://github.com/NK2552003/brew-why",
      tags: ["Python", "Textual TUI", "Homebrew", "Terminal"],
      highlight: "Interactive TUI",
      buttonText: "View on GitHub",
    },
  ]

